# Generated by generate-terraform.md, then hand-edited by the customer per
# Step 11's own instructions: the placeholder contact emails were replaced
# with real addresses. This file keeps its generated filename despite the
# edit -- which is exactly why workshop.md's Entry step 2 must never delete
# it by filename.
resource "aws_account_alternate_contact" "operations" {
  alternate_contact_type = "OPERATIONS"
  email_address          = "ops@example.com"
  name                    = "Ops Team"
  phone_number            = "+15555550100"
  title                   = "Operations"
}
