# Customer-authored, gitignored in a real run -- never regenerated by this
# skill. Committed here only as a fixture stand-in to prove it survives
# workshop re-entry untouched.
operations_email = "ops@example.com"
billing_email     = "billing@example.com"
security_email    = "security@example.com"
