#!/usr/bin/env python3
"""Sync upstream AWS skills (under reference/) into TalkOps agent and vertical plugins.

Reads scripts/aws-plugin-map.json and, for each mapped plugin:

  * copies the mapped skills (and extra dirs: commands, scripts, fixtures, ...)
  * writes the Claude Code layout: .claude-plugin/plugin.json, .mcp.json, hooks/hooks.json
  * writes the portable Agent Plugins 1.0.0 layout: plugin.json, mcp.json (Codex, Cursor, ...)
  * writes the Codex overlay .codex-plugin/plugin.json and, for agent plugins, a Codex
    custom-agent file codex/agents/<name>.toml rendered from agents/<name>.md
  * applies declared text rewrites (fails loudly if upstream drifted)
  * writes CONNECTORS.md for opt-in, connection-bound MCP servers (Claude Code and Codex snippets)
  * regenerates the plugin README.md
  * upserts the plugin entry in .claude-plugin/marketplace.json and regenerates the Codex
    marketplace .agents/plugins/marketplace.json
  * on a full sync, renders docs/mcp-server-coverage.md from mcp_upstream_index

Plugin kinds ("kind" in the map):

  * agent    -> plugins/agent-plugins/<name>/    (agents/<name>.md is hand-authored)
  * vertical -> plugins/vertical-plugins/<name>/ (commands/ is hand-authored)
  * partner  -> plugins/partner-built/<name>/    (vendor content, vendor identity; attaches to the main agent)

Hand-authored files are never touched. Re-run after pulling upstream changes:

    python3 scripts/sync_aws_plugins.py            # all plugins
    python3 scripts/sync_aws_plugins.py --only aws-sre-agent aws-networking
    python3 scripts/sync_aws_plugins.py --kind vertical
    python3 scripts/sync_aws_plugins.py --dry-run  # report only
"""

from __future__ import annotations

import argparse
import copy
import fnmatch
import json
import re
import shlex
import shutil
import sys
from pathlib import Path
from typing import Any

sys.path.insert(0, str(Path(__file__).resolve().parent))
from _plugin_lib import (  # noqa: E402
    CODEX_MARKETPLACE_PATH,
    MARKETPLACE_PATH,
    PORTABLE_MCP_SCHEMA,
    PORTABLE_PLUGIN_SCHEMA,
    REPO_ROOT,
    dump_json,
    first_sentence,
    load_json,
    mcp_tool_pattern,
    parse_frontmatter,
    split_frontmatter,
    strip_comments,
)

MAP_PATH = REPO_ROOT / "scripts" / "aws-plugin-map.json"
COVERAGE_PATH = REPO_ROOT / "docs" / "mcp-server-coverage.md"
KIND_ROOTS = {
    "agent": REPO_ROOT / "plugins" / "agent-plugins",
    "vertical": REPO_ROOT / "plugins" / "vertical-plugins",
    "partner": REPO_ROOT / "plugins" / "partner-built",
}
KIND_ORDER = {"agent": 0, "vertical": 1, "partner": 2}
# Directories the sync owns inside a plugin; they are wiped and re-copied.
# Vertical plugins own their commands/ by hand, so it is not managed there.
MANAGED_DIRS = {
    "agent": ("skills", "commands", "scripts", "fixtures", "examples", "hooks", "codex"),
    "vertical": ("skills", "scripts", "fixtures", "examples", "hooks"),
    "partner": ("skills", "commands", "scripts", "fixtures", "examples", "hooks"),
}
# Manifest fields a plugin may override (partner plugins keep the vendor's identity).
IDENTITY_OVERRIDES = ("author", "homepage", "repository", "license")
GENERATED_HEADER = (
    "<!-- Generated by scripts/sync_aws_plugins.py. Edit scripts/aws-plugin-map.json "
    "or {owned} instead, then re-run the sync. -->\n"
)
GATE_HOOK = "aws-mutation-gate"
# Env values the portable format cannot express (host-specific ${VAR:-default} expansion).
NON_PORTABLE_RE = re.compile(r"\$\{(?!PLUGIN_ROOT\}|PLUGIN_DATA\})")


class SyncError(RuntimeError):
    pass


def kind_of(plugin: dict) -> str:
    kind = plugin.get("kind", "agent")
    if kind not in KIND_ROOTS:
        raise SyncError(f"{plugin['name']}: unknown kind '{kind}'")
    return kind


def resolve_source(cfg: dict, ref: str) -> Path:
    """'toolkit/aws-core' -> <repo>/reference/agent-toolkit-for-aws/plugins/aws-core"""
    key, _, plugin = ref.partition("/")
    if key not in cfg["sources"]:
        raise SyncError(f"Unknown source key '{key}' in '{ref}'")
    path = REPO_ROOT / cfg["sources"][key]["path"] / plugin
    if not path.is_dir():
        raise SyncError(f"Source not found: {path} (is reference/ checked out?)")
    return path


def skills_root(cfg: dict, ref: str) -> Path:
    """Directory holding <skill>/SKILL.md dirs for a skill source ref.

    Plugin-style sources keep skills under <plugin>/skills; flat sources (the
    toolkit's skills/ tree) keep them directly under the referenced category.
    """
    root = resolve_source(cfg, ref)
    return root if cfg["sources"][ref.partition("/")[0]].get("flat") else root / "skills"


def resolve_rewrites(cfg: dict, entries: list) -> list[dict]:
    """Expand named templates from rewrites_catalog; inline dicts pass through."""
    out: list[dict] = []
    catalog = cfg.get("rewrites_catalog", {})
    for entry in entries:
        if isinstance(entry, str):
            if entry not in catalog:
                raise SyncError(f"Rewrite template '{entry}' not in rewrites_catalog")
            out.extend(copy.deepcopy(catalog[entry]))
        else:
            out.append(entry)
    return out


def make_ignore(patterns: list[str]):
    def _ignore(_dir: str, names: list[str]) -> set[str]:
        return {n for n in names if any(fnmatch.fnmatch(n, p) for p in patterns)}

    return _ignore


def copy_path(src: Path, dst: Path, ignore) -> None:
    if not src.exists():
        raise SyncError(f"Missing upstream path: {src}")
    dst.parent.mkdir(parents=True, exist_ok=True)
    if src.is_dir():
        shutil.copytree(src, dst, ignore=ignore, dirs_exist_ok=True, symlinks=False)
    else:
        shutil.copy2(src, dst)


def resolve_mcp(cfg: dict, entries: list) -> dict[str, Any]:
    catalog = cfg["mcp_catalog"]
    servers: dict[str, Any] = {}
    for entry in entries:
        if isinstance(entry, str):
            if entry not in catalog:
                raise SyncError(f"MCP server '{entry}' not in mcp_catalog")
            servers[entry] = copy.deepcopy(catalog[entry])
            continue
        for name, conf in entry.items():
            conf = copy.deepcopy(conf)
            ref = conf.pop("$ref", None)
            if ref:
                if ref not in catalog:
                    raise SyncError(f"MCP $ref '{ref}' not in mcp_catalog")
                base = copy.deepcopy(catalog[ref])
                base.update(conf)
                conf = base
            servers[name] = conf
    for name, conf in servers.items():
        if "disabled" in conf:
            # Claude Code ignores "disabled" in plugin .mcp.json and starts the server anyway.
            raise SyncError(f"MCP server '{name}' uses 'disabled'; model it as a connector instead")
    return servers


def mcp_notes(cfg: dict, entries: list) -> dict[str, str]:
    """Collect $comment notes per resolved server name for the README."""
    notes: dict[str, str] = {}
    catalog = cfg["mcp_catalog"]
    for entry in entries:
        if isinstance(entry, str):
            notes[entry] = catalog.get(entry, {}).get("$comment", "")
        else:
            for name, conf in entry.items():
                ref = conf.get("$ref")
                notes[name] = conf.get("$comment") or (catalog.get(ref, {}).get("$comment", "") if ref else "")
    return notes


def merge_hooks(cfg: dict, plugin: dict) -> tuple[dict, list[tuple[str, str]], list[dict]]:
    """Return (hooks_json_events, files_to_copy[(src_ref_path, dst)], rewrites)."""
    events: dict[str, list] = {}
    files: list[tuple[str, str]] = []
    rewrites: list[dict] = []
    for name in plugin.get("hooks", []):
        tpl = cfg["hooks_catalog"].get(name)
        if not tpl:
            raise SyncError(f"Hook template '{name}' not in hooks_catalog")
        for ev, items in tpl["hooks"].items():
            events.setdefault(ev, []).extend(copy.deepcopy(items))
        files.extend(tpl.get("files", {}).items())
        rewrites.extend(resolve_rewrites(cfg, tpl.get("rewrites", [])))
    for ev, items in plugin.get("hooks_inline", {}).items():
        events.setdefault(ev, []).extend(copy.deepcopy(items))
    return events, files, rewrites


def apply_rewrites(target: Path, rewrites: list[dict]) -> None:
    for rw in rewrites:
        path = target / rw["path"]
        if not path.is_file():
            raise SyncError(f"Rewrite target missing: {path}")
        text = path.read_text()
        if rw["find"] not in text:
            if rw["replace"] in text:
                continue  # already applied
            raise SyncError(f"Rewrite anchor not found in {path} (upstream drift?): {rw['find']!r}")
        path.write_text(text.replace(rw["find"], rw["replace"]))


def resolve_connectors(cfg: dict, plugin: dict) -> dict[str, dict]:
    catalog = cfg.get("connector_catalog", {})
    out: dict[str, dict] = {}
    for key in plugin.get("connectors", []):
        if key not in catalog:
            raise SyncError(f"{plugin['name']}: connector '{key}' not in connector_catalog")
        out[key] = catalog[key]
    return out


def describe_server(conf: dict) -> tuple[str, str]:
    if conf.get("url"):
        return "http", f"`{conf['url']}`"
    args = conf.get("args", [])
    if conf.get("command") == "docker":
        image = next((a for a in reversed(args) if not a.startswith("-")), "")
        return "stdio", f"`docker run {image}`"
    pkg = next((a for a in args if not a.startswith("-") and a != "--from"), "")
    if "--from" in args:
        pkg = args[args.index("--from") + 1]
    flags = " ".join(a for a in args if a.startswith("--") and a != "--from")
    return "stdio", f"`{conf.get('command', '')} {pkg}`" + (f" `{flags}`" if flags else "")


def _shell_join(parts: list[str]) -> str:
    return " ".join(shlex.quote(p) for p in parts)


def _toml_str(value: str) -> str:
    """TOML basic string. JSON string escapes (\\" \\\\ \\n \\uXXXX) are valid TOML."""
    return json.dumps(value, ensure_ascii=False)


def _toml_array(values: list[str]) -> str:
    return "[" + ", ".join(_toml_str(v) for v in values) + "]"


def connector_snippets(key: str, c: dict) -> tuple[str, str, str]:
    """(Claude Code CLI, Codex CLI, Codex config.toml) snippets for one connector."""
    env = c.get("env", {})
    launch = _shell_join([c["command"], *c.get("args", [])])
    env_flags = " ".join(f"--env {shlex.quote(f'{k}={v}')}" for k, v in env.items())
    claude = f"claude mcp add --scope user {env_flags + ' ' if env_flags else ''}{key} -- {launch}"
    codex = f"codex mcp add {key} {env_flags + ' ' if env_flags else ''}-- {launch}"
    toml = [f"[mcp_servers.{key}]", f"command = {_toml_str(c['command'])}", f"args = {_toml_array(c.get('args', []))}"]
    if env:
        toml.append("env = { " + ", ".join(f"{k} = {_toml_str(v)}" for k, v in env.items()) + " }")
    return claude, codex, "\n".join(toml)


def render_connectors(plugin: dict, connectors: dict[str, dict]) -> str:
    name = plugin["name"]
    agent_note = (
        f" In Claude Code the `{name}` agent's `tools:` allowlist already grants `mcp__<key>__*` for each key below."
        if kind_of(plugin) == "agent"
        else ""
    )
    lines = [
        GENERATED_HEADER.format(owned="the connector_catalog"),
        f"# Optional connectors: {plugin['displayName']}\n",
        "These MCP servers need a connection target (cluster endpoint, host, credentials, or a local runtime "
        "such as Docker) that only you can supply, so the plugin does **not** start them. Add the ones you need "
        "to your own agent host configuration with the exact key shown; the key determines the tool names "
        "(`mcp__<key>__*`)."
        + agent_note
        + "\n",
        "Each connector below has a Claude Code command, a Codex command, and the equivalent "
        "`~/.codex/config.toml` block. Other MCP hosts take the same `command`, `args`, and `env`.\n",
        "AWS credentials are inherited from your environment. Prefer least-privilege, read-only database "
        "users and keep write flags off unless you need them. Codex starts MCP servers with a minimal "
        "environment; if a server can't find your AWS profile, add `AWS_PROFILE` and `AWS_REGION` to its `env`.\n",
        "## Connectors\n",
        "| Key | Server | Use it for |",
        "|---|---|---|",
    ]
    for key, c in connectors.items():
        lines.append(f"| `{key}` | [`{c['package']}`]({c['docs']}) | {c['purpose']} |")
    lines.append("")
    for key, c in connectors.items():
        claude, codex, toml = connector_snippets(key, c)
        lines.append(f"### `{key}`\n")
        if c.get("setup"):
            lines += ["One-time setup:\n", "```bash", c["setup"], "```", ""]
        lines += [
            "Claude Code:\n", "```bash", claude, "```", "",
            "Codex:\n", "```bash", codex, "```", "",
            "Codex `config.toml`:\n", "```toml", toml, "```", "",
        ]
        if c.get("notes"):
            lines += [c["notes"], ""]
    return "\n".join(lines)


def portable_mcp(servers: dict[str, Any]) -> tuple[dict[str, Any], list[str]]:
    """Convert Claude-style servers to Agent Plugins 1.0.0 mcp.json entries.

    Returns (servers, notes). The portable format expands only ${PLUGIN_ROOT}/${PLUGIN_DATA}
    (in args/env/cwd), takes literal headers, and has no `timeout`; so env values with other
    ${...} expansions are dropped and remote servers that need expansion are skipped.
    """
    out: dict[str, Any] = {}
    notes: list[str] = []
    for name, conf in servers.items():
        if conf.get("url"):
            if NON_PORTABLE_RE.search(conf["url"]) or any("${" in v for v in conf.get("headers", {}).values()):
                notes.append(f"skipped {name} (needs host env expansion)")
                continue
            entry = {"type": "sse" if conf.get("type") == "sse" else "streamable-http", "url": conf["url"]}
            if conf.get("headers"):
                entry["headers"] = conf["headers"]
            out[name] = entry
            continue
        if any(NON_PORTABLE_RE.search(a) for a in conf.get("args", [])):
            notes.append(f"skipped {name} (args need host env expansion)")
            continue
        entry = {"type": "stdio", "command": conf["command"]}
        if conf.get("args"):
            entry["args"] = conf["args"]
        env = {k: v for k, v in conf.get("env", {}).items() if not NON_PORTABLE_RE.search(v)}
        if env:
            entry["env"] = env
        if conf.get("cwd"):
            entry["cwd"] = conf["cwd"]
        out[name] = entry
    return out, notes


def identity(cfg: dict, plugin: dict) -> dict[str, Any]:
    """Manifest fields shared by the Claude Code, portable, and Codex manifests.

    Defaults come from the map's `defaults`; a plugin may override IDENTITY_OVERRIDES
    (partner plugins keep the vendor's author, homepage, repository, and license).
    """
    d = cfg["defaults"]
    manifest = {
        "name": plugin["name"],
        "version": plugin.get("version", d["version"]),
        "description": plugin["description"],
    }
    manifest.update({k: plugin.get(k, d[k]) for k in IDENTITY_OVERRIDES})
    manifest["keywords"] = plugin.get("keywords", [])
    return manifest


def codex_overlay(cfg: dict, plugin: dict, has_mcp: bool, has_hooks: bool) -> dict[str, Any]:
    """.codex-plugin/plugin.json: Codex paths plus the Plugins Directory `interface` card."""
    host = cfg["hosts"]["codex"]
    manifest = identity(cfg, plugin)
    manifest["skills"] = "./skills/"
    if has_mcp:
        # The portable mcp.json, not .mcp.json: Codex does not expand ${VAR:-default}.
        manifest["mcpServers"] = "./mcp.json"
    if has_hooks:
        manifest["hooks"] = "./hooks/hooks.json"
    kind = kind_of(plugin)
    interface = {
        "displayName": plugin["displayName"],
        "shortDescription": first_sentence(re.split(r"[:;]\s|\.\s", plugin["description"])[0], 120),
        "longDescription": plugin["description"],
        "developerName": host["developerName"],
        "category": host["category"],
        "capabilities": ["Read"] if plugin.get("aws_read_only") else ["Read", "Write"],
        "websiteURL": f"{host['websiteURL']}/tree/main/{KIND_ROOTS[kind].relative_to(REPO_ROOT).as_posix()}/{plugin['name']}",
        "brandColor": host["brandColor"],
    }
    if plugin.get("defaultPrompt"):
        interface["defaultPrompt"] = plugin["defaultPrompt"][:3]
    interface.update(plugin.get("codex_interface", {}))
    manifest["interface"] = interface
    return manifest


def render_codex_agent(plugin: dict, agent_md: Path) -> str:
    """Codex custom agent (~/.codex/agents/<name>.toml) from the hand-authored Claude agent file."""
    text = agent_md.read_text()
    fm = parse_frontmatter(text)
    _, body = split_frontmatter(text)
    name = plugin["name"]
    preamble = (
        f"You are running as a Codex custom agent built from the {name} plugin. "
        "When this prompt names an MCP tool as mcp__plugin_<plugin>_<server>__<tool>, use the same tool as "
        "mcp__<server>__<tool>. Claude Code-only features this prompt mentions (the Skill tool, TodoWrite, "
        "slash commands) map to Codex skills, your plan, and plain instructions."
    )
    if plugin.get("aws_read_only"):
        preamble += (
            " You are read-only on AWS: never run commands or MCP calls that create, change, or delete AWS "
            "resources. Hand those to the user or the owning agent instead."
        )
    instructions = preamble + "\n\n" + body.strip() + "\n"
    if "'''" in instructions:
        dev = _toml_str(instructions)
    else:
        dev = "'''\n" + instructions + "'''"
    return "\n".join([
        f"# Generated by scripts/sync_aws_plugins.py from agents/{name}.md. Do not edit.",
        f"# Install: copy to ~/.codex/agents/ (or <project>/.codex/agents/) and install the {name} plugin",
        "# so its skills and MCP servers are available to this agent.",
        f"name = {_toml_str(name)}",
        f"description = {_toml_str(fm.get('description', plugin['description']))}",
        f"developer_instructions = {dev}",
        "",
    ])


def read_only_agents(cfg: dict) -> list[str]:
    return [p["name"] for p in cfg["plugins"] if p.get("aws_read_only")]


def render_readme(
    cfg: dict, plugin: dict, target: Path, servers: dict, notes: dict, hook_events: dict, connectors: dict
) -> str:
    name = plugin["name"]
    kind = kind_of(plugin)
    owned = {"agent": f"agents/{name}.md", "vertical": "commands/*.md", "partner": "the upstream vendor repository"}[kind]
    lines = [GENERATED_HEADER.format(owned=owned), f"# {plugin['displayName']}\n", f"{plugin['description']}\n"]
    market = cfg["marketplace"]["name"]
    portable = "[`plugin.json`](./plugin.json), `skills/`, and [`mcp.json`](./mcp.json)" if servers else (
        "[`plugin.json`](./plugin.json) and `skills/`"
    )
    lines += [
        "## Install\n",
        "| Host | How |",
        "|---|---|",
        f"| Claude Code | `/plugin marketplace add talkops-ai/devops-plugins`, then `/plugin install {name}@{market}` |",
        "| Codex | `codex plugin marketplace add talkops-ai/devops-plugins`, then install from the Plugins Directory"
        + (f"; for the agent persona, copy [`codex/agents/{name}.toml`](./codex/agents/{name}.toml) to `~/.codex/agents/`"
           if kind == "agent" else "")
        + " |",
        f"| Other Agent Plugins hosts | Load this directory; {portable} follow the portable "
        "[Agent Plugins](https://agent-plugins.org) format |",
        "",
    ]
    if kind == "agent":
        lines.append("## Agent\n")
        lines.append(
            f"This is an **agent plugin**: every skill, command, hook, and MCP server below is bound to the "
            f"[`{name}`](./agents/{name}.md) agent, which the host runtime spawns as a dynamic sub-agent.\n"
        )
        lines.append(f"- Claude Code: `@agent-{name}:{name}` or let Claude delegate based on the agent description")
        lines.append(f"- Headless: `claude --agent {name}:{name}`")
        lines.append(
            f"- Codex: install the custom agent above, then ask Codex to spawn `{name}`. Codex plugins can't "
            "bundle agents, so without it the skills and MCP servers attach to the main agent."
        )
        if plugin.get("aws_read_only"):
            lines.append(
                "- **Read-only on AWS.** `aws-mcp` runs with `--read-only`, and the `aws-mutation-gate` hook denies "
                "mutating shell/MCP calls from this agent in Claude Code. Pair it with a read-only AWS profile."
            )
        kinds = {p["name"]: kind_of(p) for p in cfg["plugins"]}
        for comp in plugin.get("companions", []):
            if comp not in kinds:
                raise SyncError(f"{name}: companion '{comp}' is not a plugin in the map")
            rel = KIND_ROOTS[kinds[comp]].relative_to(REPO_ROOT / "plugins").as_posix()
            lines.append(
                f"- **Companion plugin:** install [`{comp}`](../../{rel}/{comp}) alongside this one "
                f"(`/plugin install {comp}@{market}`); the agent uses its skills when they are present."
            )
        lines.append("")
    else:
        agents = plugin.get("agents", [])
        alt = (
            " or ".join(f"[`{a}`](../../agent-plugins/{a})" for a in agents) + " agent plugin"
            if agents
            else "the matching agent plugin"
        )
        lines.append("## How it works\n")
        if kind == "partner":
            vendor = plugin.get("author", cfg["defaults"]["author"])["name"]
            prefer = (
                f" Prefer the {alt} when you want an isolated specialist that applies these practices to AWS "
                "with approval gates."
                if agents
                else ""
            )
            lines.append(
                f"This is a **partner-built plugin**: {vendor}'s official content, copied unmodified and "
                f"redistributed under its {plugin.get('license', cfg['defaults']['license'])} license. Its skills attach "
                f"directly to your main agent, with no sub-agent hand-off.{prefer}\n"
            )
        else:
            lines.append(
                "This is a **vertical plugin**: its skills, commands, and MCP servers attach directly to your main "
                f"agent, with no sub-agent hand-off. Prefer the {alt} when you want an isolated specialist instead.\n"
            )
        lines.append(f"- Skills activate from their descriptions; in Claude Code invoke one explicitly with `/{name}:<skill>`\n")

    skills_dir = target / "skills"
    rows = []
    for d in sorted(p for p in skills_dir.iterdir() if p.is_dir()) if skills_dir.is_dir() else []:
        skill_md = d / "SKILL.md"
        if not skill_md.is_file():
            continue
        fm = parse_frontmatter(skill_md.read_text(errors="ignore"))
        rows.append(f"| `{fm.get('name', d.name)}` | {first_sentence(fm.get('description', ''))} |")
    if rows:
        lines += ["## Skills\n", "| Skill | What it does |", "|---|---|", *rows, ""]

    cmd_dir = target / "commands"
    if cmd_dir.is_dir():
        crow = []
        for f in sorted(cmd_dir.glob("*.md")):
            fm = parse_frontmatter(f.read_text(errors="ignore"))
            crow.append(f"| `/{name}:{f.stem}` | {first_sentence(fm.get('description', ''))} |")
        if crow:
            lines += ["## Commands\n", "| Command | Description |", "|---|---|", *crow, ""]

    agents_dir = target / "agents"
    workers = sorted(p for p in agents_dir.glob("*.md") if p.stem != name) if agents_dir.is_dir() else []
    if workers:
        lines += ["## Worker agents\n", "Dispatched by the orchestrating agent's skills; not meant for direct conversation.\n"]
        for w in workers:
            fm = parse_frontmatter(w.read_text(errors="ignore"))
            lines.append(f"- `{name}:{w.stem}` — {first_sentence(fm.get('description', ''), 160)}")
        lines.append("")

    if servers:
        if kind == "agent":
            intro = (
                "Declared in [`.mcp.json`](./.mcp.json) (Claude Code) and [`mcp.json`](./mcp.json) (portable). "
                "In Claude Code they are bound to the agent through its `tools:` allowlist.\n"
            )
            col = "Claude Code tool pattern"
        else:
            intro = (
                "Declared in [`.mcp.json`](./.mcp.json) (Claude Code) and [`mcp.json`](./mcp.json) (portable); "
                "started when the plugin is enabled and available to the main agent.\n"
            )
            col = "Claude Code tool names"
        lines += [
            "## MCP servers\n",
            intro,
            f"| Server | Transport | Launch | {col} | Notes |",
            "|---|---|---|---|---|",
        ]
        for sname, conf in servers.items():
            transport, launch = describe_server(conf)
            lines.append(
                f"| `{sname}` | {transport} | {launch} | `{mcp_tool_pattern(name, sname)}` | {notes.get(sname, '')} |"
            )
        lines += [
            "",
            "AWS credentials are inherited from the host environment (`AWS_PROFILE`, SSO, or instance role). "
            "In Claude Code `AWS_REGION` defaults to `us-east-1` when unset; the portable `mcp.json` can't express "
            "that default, so set `AWS_REGION` in your environment on other hosts. Codex starts MCP servers with a "
            "minimal environment: if a server can't see your profile, set `AWS_PROFILE`/`AWS_REGION` for it in "
            "`~/.codex/config.toml`.\n",
        ]

    if connectors:
        lines += [
            "## Optional connectors\n",
            "Connection-bound MCP servers you add yourself (see [CONNECTORS.md](./CONNECTORS.md)): "
            + ", ".join(f"`{k}`" for k in connectors)
            + ".\n",
        ]

    if hook_events:
        lines += ["## Hooks\n"]
        for ev, items in hook_events.items():
            for it in items:
                matcher = it.get("matcher", "*")
                for h in it.get("hooks", []):
                    what = h.get("command") or h.get("prompt", "")
                    what = first_sentence(what, 140).replace("|", "\\|")
                    lines.append(f"- **{ev}** `{matcher}` — {h.get('type')}: `{what}`")
        lines.append("")

    lines += ["## Upstream\n", "Derived from the following open-source sources (see the repository `NOTICE`):\n"]
    for up in plugin.get("upstream", []):
        src = cfg["sources"][up["source"]]
        lines.append(
            f"- [`{up['plugin']}`]({src['upstream']}) ({src['upstream'].split('github.com/')[-1]}, "
            f"{src.get('license', 'Apache-2.0')})"
        )
    lines.append("")
    return "\n".join(lines)


def sync_plugin(cfg: dict, plugin: dict, dry_run: bool) -> list[str]:
    name = plugin["name"]
    kind = kind_of(plugin)
    target = KIND_ROOTS[kind] / name
    ignore = make_ignore(cfg["exclude"])
    log: list[str] = []

    # Some partner plugins are authored in this repository rather than mirrored
    # from an upstream source. Keep their hand-authored package intact while
    # still registering them in both generated marketplace catalogs.
    if kind == "partner" and plugin.get("local"):
        if not target.is_dir():
            raise SyncError(f"{name}: local partner plugin not found at {target}")
        return [f"{name} ({kind}): local package preserved"]

    if dry_run:
        for spec in plugin["skills"]:
            skills_root(cfg, spec["from"])
        resolve_connectors(cfg, plugin)
        resolve_mcp(cfg, plugin.get("mcp", []))
        return [f"[dry-run] {name} ({kind}): sources resolved"]

    target.mkdir(parents=True, exist_ok=True)
    for d in MANAGED_DIRS[kind]:
        shutil.rmtree(target / d, ignore_errors=True)
    agents_dir = target / "agents"
    if kind == "agent" and agents_dir.is_dir():
        for f in agents_dir.iterdir():
            if f.is_file() and f.name != f"{name}.md":
                f.unlink()

    # Skills
    count = 0
    for spec in plugin["skills"]:
        src = skills_root(cfg, spec["from"])
        names = spec["names"]
        chosen = sorted(p.name for p in src.iterdir() if p.is_dir()) if names == "*" else names
        for skill in chosen:
            if skill in spec.get("except", []):
                continue
            dst = target / "skills" / skill
            if dst.exists():
                raise SyncError(f"{name}: skill '{skill}' is mapped twice")
            copy_path(src / skill, dst, ignore)
            count += 1
    log.append(f"{count} skill dirs")

    # Extra paths
    for spec in plugin.get("copy", []):
        src_root = resolve_source(cfg, spec["from"])
        paths = spec["paths"]
        mapping = paths.items() if isinstance(paths, dict) else ((p, p) for p in paths)
        for s, d in mapping:
            copy_path(src_root / s, target / d, ignore)
            log.append(f"copied {s}")

    # Hooks
    events, hook_files, hook_rewrites = merge_hooks(cfg, plugin)
    for src_ref, dst in hook_files:
        key, _, rest = src_ref.partition("/")
        plugin_name, _, rel = rest.partition("/")
        copy_path(resolve_source(cfg, f"{key}/{plugin_name}") / rel, target / dst, ignore)
    if events:
        dump_json(target / "hooks" / "hooks.json", {"hooks": events})
        log.append(f"hooks: {', '.join(events)}")
    if GATE_HOOK in plugin.get("hooks", []):
        dump_json(target / "hooks" / f"{GATE_HOOK}.json", {"read_only_agents": read_only_agents(cfg)})

    apply_rewrites(target, hook_rewrites + resolve_rewrites(cfg, plugin.get("rewrites", [])))

    # MCP
    servers = resolve_mcp(cfg, plugin.get("mcp", []))
    clean_servers = strip_comments(servers)
    mcp_path = target / ".mcp.json"
    if clean_servers:
        dump_json(mcp_path, {"mcpServers": clean_servers})
    elif mcp_path.exists():
        mcp_path.unlink()
    log.append(f"mcp: {', '.join(clean_servers) or 'none'}")

    # Connectors (opt-in, user-configured MCP servers)
    connectors = resolve_connectors(cfg, plugin)
    conn_path = target / "CONNECTORS.md"
    if connectors:
        conn_path.write_text(render_connectors(plugin, connectors))
        log.append(f"connectors: {', '.join(connectors)}")
    elif conn_path.exists():
        conn_path.unlink()

    # Portable Agent Plugins 1.0.0 layout (Codex, Cursor, Copilot, ...)
    portable, portable_notes = portable_mcp(clean_servers)
    portable_path = target / "mcp.json"
    if portable:
        dump_json(portable_path, {"$schema": PORTABLE_MCP_SCHEMA, "mcpServers": portable})
    elif portable_path.exists():
        portable_path.unlink()
    log.extend(f"mcp.json: {n}" for n in portable_notes)
    manifest = identity(cfg, plugin)
    dump_json(target / "plugin.json", {"$schema": PORTABLE_PLUGIN_SCHEMA, **manifest})

    # Claude Code and Codex manifests
    dump_json(target / ".claude-plugin" / "plugin.json", manifest)
    dump_json(target / ".codex-plugin" / "plugin.json", codex_overlay(cfg, plugin, bool(portable), bool(events)))
    if kind == "agent" and (agents_dir / f"{name}.md").is_file():
        toml_path = target / "codex" / "agents" / f"{name}.toml"
        toml_path.parent.mkdir(parents=True, exist_ok=True)
        toml_path.write_text(render_codex_agent(plugin, agents_dir / f"{name}.md"))

    # README
    (target / "README.md").write_text(
        render_readme(cfg, plugin, target, clean_servers, mcp_notes(cfg, plugin.get("mcp", [])), events, connectors)
    )

    if kind == "agent" and not (agents_dir / f"{name}.md").is_file():
        log.append(f"WARNING: hand-authored agents/{name}.md is missing")
    if kind == "vertical" and not any((target / "commands").glob("*.md")):
        log.append("note: no hand-authored commands/")
    return [f"{name} ({kind}): " + "; ".join(log)]


def upsert_marketplace(cfg: dict, plugins: list[dict]) -> None:
    mp = load_json(MARKETPLACE_PATH) if MARKETPLACE_PATH.exists() else {}
    mp.setdefault("name", cfg["marketplace"]["name"])
    mp.setdefault("owner", cfg["marketplace"]["owner"])
    mp["metadata"] = cfg["marketplace"]["metadata"]
    entries = mp.setdefault("plugins", [])
    index = {e["name"]: i for i, e in enumerate(entries)}
    for p in plugins:
        kind = kind_of(p)
        entry = {
            "name": p["name"],
            "displayName": p["displayName"],
            "source": f"./{KIND_ROOTS[kind].relative_to(REPO_ROOT).as_posix()}/{p['name']}",
            "description": p["description"],
            "version": p.get("version", cfg["defaults"]["version"]),
            "category": p["category"],
            "keywords": p.get("keywords", []),
        }
        for key in IDENTITY_OVERRIDES:
            if key in p:
                entry[key] = p[key]
        if p["name"] in index:
            entries[index[p["name"]]] = entry
        else:
            entries.append(entry)
    # Agent plugins first, then verticals, then partner-built, each in map order.
    order = {p["name"]: i for i, p in enumerate(cfg["plugins"])}
    roots = {KIND_ROOTS[k].relative_to(REPO_ROOT).as_posix(): v for k, v in KIND_ORDER.items()}
    entries.sort(
        key=lambda e: (roots.get(str(e["source"])[2:].rsplit("/", 1)[0], 99), order.get(e["name"], 10_000))
    )
    dump_json(MARKETPLACE_PATH, mp)


def write_codex_marketplace(cfg: dict) -> int:
    """Regenerate .agents/plugins/marketplace.json (Codex repo marketplace) from every mapped plugin.

    Codex reads .agents/plugins/marketplace.json (falling back to .claude-plugin/marketplace.json);
    it does not read a root .codex-plugin/marketplace.json, so a stale one is removed.
    """
    host = cfg["hosts"]["codex"]
    plugins = sorted(cfg["plugins"], key=lambda p: KIND_ORDER[kind_of(p)])
    mp = {
        "name": cfg["marketplace"]["name"],
        "interface": {"displayName": host["marketplaceDisplayName"]},
        "plugins": [
            {
                "name": p["name"],
                "source": {"source": "local", "path": f"./{KIND_ROOTS[kind_of(p)].relative_to(REPO_ROOT).as_posix()}/{p['name']}"},
                "policy": host["policy"],
                "category": p.get("codex_interface", {}).get("category", host["category"]),
            }
            for p in plugins
        ],
    }
    dump_json(CODEX_MARKETPLACE_PATH, mp)
    stale = REPO_ROOT / ".codex-plugin" / "marketplace.json"
    if stale.exists():
        stale.unlink()
        if not any(stale.parent.iterdir()):
            stale.parent.rmdir()
    return len(plugins)


def server_keys(entries: list) -> list[str]:
    """Catalog keys behind a plugin's mcp entries (inline servers count under their own name)."""
    keys: list[str] = []
    for entry in entries:
        if isinstance(entry, str):
            keys.append(entry)
        else:
            keys.extend(conf.get("$ref", name) for name, conf in entry.items())
    return keys


def render_mcp_coverage(cfg: dict) -> str:
    index = cfg["mcp_upstream_index"]
    src_dir = REPO_ROOT / index["path"]
    servers = index["servers"]
    if src_dir.is_dir():
        missing = sorted(p.name for p in src_dir.iterdir() if p.is_dir() and p.name not in servers)
        if missing:
            raise SyncError(f"mcp_upstream_index is missing upstream server(s): {', '.join(missing)}")
    connectors = cfg.get("connector_catalog", {})
    for d, info in servers.items():
        key = info.get("key")
        if key and key not in cfg["mcp_catalog"] and key not in connectors:
            raise SyncError(f"mcp_upstream_index: '{d}' -> '{key}' is not in mcp_catalog or connector_catalog")

    used: dict[str, dict[str, list[str]]] = {}
    for p in cfg["plugins"]:
        kind = kind_of(p)
        for key in server_keys(p.get("mcp", [])) + p.get("connectors", []):
            bucket = used.setdefault(key, {k: [] for k in KIND_ROOTS})[kind]
            if p["name"] not in bucket:
                bucket.append(p["name"])

    def links(names: list[str], kind: str) -> str:
        root = KIND_ROOTS[kind].relative_to(REPO_ROOT).as_posix()
        return ", ".join(f"[`{n}`](../{root}/{n})" for n in names) or "—"

    def cols(key: str) -> str:
        return " | ".join(links(used[key][k], k) for k in KIND_ROOTS)

    head = " | ".join(f"{k.capitalize()} plugins" for k in KIND_ROOTS)
    sep = "|---" * len(KIND_ROOTS)

    up = index["upstream"]
    bundled = [(d, i["key"]) for d, i in servers.items() if i.get("key") and i["key"] not in connectors]
    conns = [(d, i["key"]) for d, i in servers.items() if i.get("key") in connectors]
    skipped = [(d, i["skip"]) for d, i in servers.items() if "skip" in i]
    unused = [k for _, k in bundled + conns if k not in used]
    if unused:
        raise SyncError(f"mcp_upstream_index maps to key(s) no plugin uses: {', '.join(unused)}")

    lines = [
        GENERATED_HEADER.format(owned="mcp_upstream_index"),
        "# MCP server coverage\n",
        f"How each server in [awslabs/mcp]({up}) is used by the TalkOps AWS plugins: "
        f"**{len(bundled)} bundled**, **{len(conns)} connectors**, **{len(skipped)} not used** "
        f"({len(servers)} total).\n",
        "- **Bundled** servers are declared in the plugin's `.mcp.json` (Claude Code) and `mcp.json` (portable "
        "Agent Plugins format, read by Codex and other hosts) and start when the plugin is enabled. "
        "They need only AWS credentials, and default to read-only where the server supports it.",
        "- **Connectors** need a connection target (endpoint, host, credentials secret, or local runtime) at "
        "startup. Plugins document them in `CONNECTORS.md` with Claude Code (`claude mcp add`) and Codex "
        "(`codex mcp add` / `config.toml`) snippets. Plugin MCP files have no reliable \"disabled\" switch "
        "across hosts (Claude Code ignores it; the portable schema has none), so they are never shipped disabled.\n",
        "## Bundled servers\n",
        f"| Upstream server | Key | {head} |",
        f"|---|---{sep}|",
    ]
    for d, key in bundled:
        lines.append(f"| [`{d}`]({up}/tree/main/src/{d}) | `{key}` | {cols(key)} |")
    lines += ["", "## Connectors\n", f"| Upstream server | Key | {head} |", f"|---|---{sep}|"]
    for d, key in conns:
        lines.append(f"| [`{d}`]({up}/tree/main/src/{d}) | `{key}` | {cols(key)} |")
    lines += ["", "## Not used\n", "| Upstream server | Why |", "|---|---|"]
    for d, reason in skipped:
        lines.append(f"| [`{d}`]({up}/tree/main/src/{d}) | {reason} |")

    indexed = {k for _, k in bundled + conns}
    others = [k for k in used if k not in indexed]
    if others:
        lines += ["", "## Other MCP servers\n", "Servers that do not come from awslabs/mcp.\n",
                  f"| Key | How | Endpoint | {head} |", f"|---|---|---{sep}|"]
        for key in others:
            how = "connector" if key in connectors else "bundled"
            conf = cfg["mcp_catalog"].get(key) or connectors.get(key)
            if conf is None:
                conf = next(
                    (e[key] for p in cfg["plugins"] for e in p.get("mcp", []) if isinstance(e, dict) and key in e), {}
                )
            _, launch = describe_server(conf)
            lines.append(f"| `{key}` | {how} | {launch} | {cols(key)} |")
    lines.append("")
    return "\n".join(lines)


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--only", nargs="*", help="plugin names to sync (default: all)")
    ap.add_argument("--kind", choices=sorted(KIND_ROOTS), help="only sync plugins of this kind")
    ap.add_argument("--dry-run", action="store_true")
    args = ap.parse_args()

    cfg = load_json(MAP_PATH)
    plugins = cfg["plugins"]
    names = [p["name"] for p in plugins]
    dupes = {n for n in names if names.count(n) > 1}
    if dupes:
        print(f"Duplicate plugin name(s) in map: {', '.join(sorted(dupes))}", file=sys.stderr)
        return 2
    if args.kind:
        plugins = [p for p in plugins if p.get("kind", "agent") == args.kind]
    if args.only:
        unknown = set(args.only) - set(names)
        if unknown:
            print(f"Unknown plugin(s): {', '.join(sorted(unknown))}", file=sys.stderr)
            return 2
        plugins = [p for p in plugins if p["name"] in args.only]

    try:
        for p in plugins:
            for line in sync_plugin(cfg, p, args.dry_run):
                print(line)
        if not args.dry_run:
            upsert_marketplace(cfg, plugins)
            print(f"marketplace: {MARKETPLACE_PATH.relative_to(REPO_ROOT)} updated ({len(plugins)} entries upserted)")
            n = write_codex_marketplace(cfg)
            print(f"marketplace: {CODEX_MARKETPLACE_PATH.relative_to(REPO_ROOT)} written ({n} entries)")
        coverage = render_mcp_coverage(cfg) if "mcp_upstream_index" in cfg else None
        if coverage and not (args.dry_run or args.only or args.kind):
            COVERAGE_PATH.parent.mkdir(parents=True, exist_ok=True)
            COVERAGE_PATH.write_text(coverage)
            print(f"coverage: {COVERAGE_PATH.relative_to(REPO_ROOT)} written")
    except SyncError as exc:
        print(f"ERROR: {exc}", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
